apiVersion: v1
kind: Endpoints
metadata:
  name: logging-es-ops-gluster
subsets:
- addresses:
  - ip: 192.168.191.56
  ports:
  - port: 1
- addresses:
  - ip: 192.168.191.57
  ports:
  - port: 1
- addresses:
  - ip: 192.168.191.58
  ports:
  - port: 1
